"""
config
"""

# 图片处理设置
HASH_METHOD = "average"
HASH_SIZE = 16

# 用时目标（秒）
AVG_TIME = 0.4 # 平均用时不能超过
MAX_TIME = 1.0 # 单个最长用时不能超过

# 准确度目标
CHALLENGE_HASH_DIFF_THRESHOLD = 0.08
BASE_HASH_DIFF_THRESHOLD = 0.15
CHALLENGE_HASH_DIFF_BYTES = HASH_SIZE ** 2 * CHALLENGE_HASH_DIFF_THRESHOLD
BASE_HASH_DIFF_BYTES = HASH_SIZE ** 2 * BASE_HASH_DIFF_THRESHOLD

print(f"{CHALLENGE_HASH_DIFF_BYTES=}")
print(f"{BASE_HASH_DIFF_BYTES=}")
